CREATE TABLE  "COMPANY_MAILER_USER" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(4000), 
	"EMAIL" VARCHAR2(4000), 
	"PASSWORD" VARCHAR2(4000), 
	"GENDER" VARCHAR2(4000), 
	"DOB" DATE, 
	"ADDRESSLINE" VARCHAR2(4000), 
	"CITY" VARCHAR2(4000), 
	"STATE" VARCHAR2(4000), 
	"COUNTRY" VARCHAR2(4000), 
	"CONTACT" VARCHAR2(4000), 
	"REGISTEREDDATE" DATE, 
	"AUTHORIZED" VARCHAR2(4000), 
	 CONSTRAINT "COMPANY_MAILER_USER_PK" PRIMARY KEY ("ID") ENABLE
   )
/

CREATE TABLE  "COMPANY_MAILER_MESSAGE" 
   (	"ID" NUMBER, 
	"SENDER" VARCHAR2(4000), 
	"RECEIVER" VARCHAR2(4000), 
	"SUBJECT" VARCHAR2(4000), 
	"MESSAGE" VARCHAR2(4000), 
	"TRASH" VARCHAR2(4000), 
	"MESSAGEDATE" DATE, 
	 CONSTRAINT "COMPANY_MAILER_MESSAGE_PK" PRIMARY KEY ("ID") ENABLE
   )
/


--postgres

CREATE TABLE  COMPANY_MAILER_USER 
   (	ID SERIAL, 
	NAME CHARACTER VARYING(4000), 
	EMAIL CHARACTER VARYING(4000), 
	PASSWORD CHARACTER VARYING(4000), 
	GENDER CHARACTER VARYING(4000), 
	DOB DATE, 
	ADDRESSLINE CHARACTER VARYING(4000), 
	CITY CHARACTER VARYING(4000), 
	STATE CHARACTER VARYING(4000), 
	COUNTRY CHARACTER VARYING(4000), 
	CONTACT CHARACTER VARYING(4000), 
	REGISTEREDDATE DATE, 
	AUTHORIZED CHARACTER VARYING(4000), 
	 CONSTRAINT COMPANY_MAILER_USER_PK PRIMARY KEY (ID)
   )
/

CREATE TABLE  COMPANY_MAILER_MESSAGE 
   (	ID SERIAL, 
	SENDER CHARACTER VARYING(4000), 
	RECEIVER CHARACTER VARYING(4000), 
	SUBJECT CHARACTER VARYING(4000), 
	MESSAGE CHARACTER VARYING(4000), 
	TRASH CHARACTER VARYING(4000), 
	MESSAGEDATE DATE, 
	 CONSTRAINT COMPANY_MAILER_MESSAGE_PK PRIMARY KEY (ID)
   )
/